name: 'tipster'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" 
clean-targets:
  - "target"
  - "dbt_packages"

snapshots:
  tipster:
    fivethirtyeight:
      +target_schema: fivethirtyeight
      spi:
        strategy: check
        unique_key: date || ' - ' || team1 || ' - ' || team2
        check_cols: all
    tipster:
      +target_schema: tipster
      fct_h2h:
        strategy: check
        unique_key: id || ' - '  || bookmaker_key || ' - ' || user
        check_cols: all

models:
  tipster:
