name: 'tipster'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" 
clean-targets:
  - "target"
  - "dbt_packages"

snapshots:
  tipster:
    fivethirtyeight:
      +target_schema: fivethirtyeight
      spi:
        strategy: check
        unique_key: date || ' - ' || team1 || ' - ' || team2
        check_cols: all

    theoddsapi:
      +target_schema: theoddsapi
      odds:
        strategy: check
        unique_key: id || ' - ' || bookmaker_key || ' - ' || market_key
        check_cols:
          - commence_time
          - price_home_team
          - price_draw
          - price_away_team

    tipster:
      +target_schema: tipster
      fct_h2h:
        strategy: check
        unique_key: id || ' - '  || bet || ' - ' || bookmaker_key
        check_cols:
          - start_at
          - price
          - prob
          - quality
          - importance
          - rating
          - market_count
          - market_price_min
          - market_price_median
          - market_price_max


models:
  tipster:

on-run-start:
  - '{{ create_udfs() }}'
