version: 2

sources:
  - name: fivethirtyeight
    freshness:
      error_after:
        count: 12
        period: hour
    loaded_at_field: loaded_at
    tables:
      - name: spi

  - name: theoddsapi
    freshness:
      error_after:
        count: 24
        period: hour
    loaded_at_field: loaded_at
    tables:
      - name: odds

  - name: tipster
    tables:
      - name: sent
