version: 2

sources:
  - name: fivethirtyeight
    freshness:
      error_after:
        count: 1
        period: hour
    loaded_at_field: loaded_at
    tables:
      - name: spi

  - name: theoddsapi
    freshness:
      error_after:
        count: 3
        period: hour
    loaded_at_field: loaded_at
    tables:
      - name: odds

  - name: tipster
    tables:
      - name: sent
      - name: bet
      - name: ignore
      - name: user_bankroll
      - name: user_bookmaker
      - name: user_ev
      - name: user_kelly
      - name: user_league
