version: 2

models:
  - name: stg_spi
    description: Fivethirtyeight Soccer Power Index
    columns:
      - name: home
        description: Home team name
        tests:
          - not_null
      - name: away
        description: Away team name
        tests:
          - not_null

  - name: stg_odds
    description: The Odds API lines
    columns:
      - name: home
        description: Home team name
        tests:
          - not_null
      - name: away
        description: Away team name
        tests:
          - not_null