name: Deploy

on:

  push:
    branches:
      - main
      - dev

    paths:
      - stackoverflow/**
      - .github/workflows/deploy-stackoverflow.yml

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.REF_NAME }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Authenticate Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_KEYFILE }}
      
      - name: Update Google Cloud Schedule
        run: |
          gcloud scheduler jobs update pubsub stackoverflow \
            --location=us-east4 \
            --schedule="0 */12 * * *" \
            --topic=etl \
            --message-body="foo"

      - name: Deploy Function
        uses: google-github-actions/deploy-cloud-functions@v1
        with:
          name: stackoverflow
          runtime: python310
          source_dir: stackoverflow
          entry_point: handler
          memory_mb: 512
          region: us-east4
          service_account_email: ${{ secrets.GCP_ETL_SERVICE_ACCOUNT }}
          event_trigger_type: providers/cloud.pubsub/eventTypes/topic.publish
          event_trigger_resource: stackoverflow
