name: Deploy Telegram

on:

  push:
    branches:
      - main
      - dev

    paths:
      - telegram/**
      - .github/workflows/telegram-deploy.yml

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.REF_NAME }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - id: auth
        name: Authenticate Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_KEYFILE }}
      
      - name: Update Google Cloud Schedule
        run: |
          gcloud scheduler jobs update pubsub telegram \
            --location=us-east4 \
            --schedule="0 * * * *" \
            --time-zone="America/Sao_Paulo" \
            --topic=telegram \
            --message-body="foo"

      - name: Deploy Function
        uses: google-github-actions/deploy-cloud-functions@v1
        with:
          name: telegram
          runtime: python310
          source_dir: telegram
          entry_point: handler
          memory_mb: 256
          timeout: 3600
          region: us-east4
          service_account_email: telegram@${{ steps.auth.outputs.project_id }}.iam.gserviceaccount.com
          event_trigger_type: providers/cloud.pubsub/eventTypes/topic.publish
          event_trigger_resource: projects/${{ steps.auth.outputs.project_id }}/topics/telegram
          env_vars: TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }},TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}
