name: Deploy TheOddsAPI

on:

  push:
    branches:
      - main
      - dev

    paths:
      - theoddsapi/**
      - .github/workflows/theoddsapi-deploy.yml

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.REF_NAME }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - id: auth
        name: Authenticate Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_KEYFILE }}
      
      - name: Update Google Cloud Schedule
        run: |
          gcloud scheduler jobs update pubsub theoddsapi \
            --location=us-east4 \
            --schedule="59 2,14 * * *" \
            --time-zone="America/Sao_Paulo" \
            --topic=theoddsapi \
            --message-body="foo"

      - name: Deploy Function
        uses: google-github-actions/deploy-cloud-functions@v1
        with:
          name: theoddsapi
          runtime: python310
          source_dir: theoddsapi
          entry_point: handler
          memory_mb: 512
          timeout: 60
          region: us-east4
          service_account_email: extract-transform-load@${{ steps.auth.outputs.project_id }}.iam.gserviceaccount.com
          event_trigger_type: providers/cloud.pubsub/eventTypes/topic.publish
          event_trigger_resource: projects/${{ steps.auth.outputs.project_id }}/topics/theoddsapi
          env_vars: THE_ODDS_API_KEY=${{ secrets.THE_ODDS_API_KEY }}
